### ISSUE TITLE
借鉴goframe封装

### ISSUE THREAD

**Issue by HHC26** [golang-acexy/starter-gin#26]
借鉴goframe封装req和res 在使用上会不会更加简单呢

**Comment by HHC26** [comment]
1、ORM 支持： 集成 GORM ORM 框架，简化数据库操作，提供丰富的功能，如结构映射、查询构建、关联关系等，提升开发效率。
2、高性能路由： 完全兼容net/http，使用 gorilla/mux 构建高性能的 HTTP 路由系统，支持 URL 参数、正则表达式匹配等功能，灵活配置路由规则。
3、API 自动绑定： API 定义与控制器自动绑定，API参数自动校验，简化 API 开发流程，提高开发效率。
4、OpenAPI 文档自动生成： 支持自动生成 OpenAPI 规范文档，方便 API 的调试和集成。

**Comment by acexy** [comment]
是的哦，还有很大的空间，但是没时间一步到位，只有在有限的时间慢慢迭代，谢谢建议。
